theme: minima
title: Purple Hack
description: Dungeons & Dragons House Rules
minima:
  skin: auto
  nav-pages:
    - README.md
    - README.md#Character-Creation
    - background.md
    - equipmentupgrades.md
